# 本地开发环境配置
spring:
  datasource:
    url: jdbc:postgresql://47.94.247.12:5432/yuca?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  data:
    redis:
      host: 47.94.247.12

minio:
  endpoint: http://47.94.247.12:9000
